#!/bin/sh

alias p='pacman --color=auto'
alias sp='sudo pacman -S --noconfirm'

alias cat='cat -s'
alias docker='sudo docker'
alias diff='diff --color=auto -u'
alias du='du -h'
alias df='df -h'
alias grep='grep --color=auto -E'
alias ls='ls -v --color=auto'
alias ll='ls -lAhF'
alias o='xdg-open'
alias rd='rm -rf'
alias server='python3 -m http.server'
alias ssn='shutdown now'
alias xc='xsel -ib'
alias xp='xsel -ob'
alias .1='cd ..'
alias .2='cd ../..'
alias playtime='cd ~/src/go/playground && vim main.go'
alias vimconf='vim .config/nvim/init.lua'

alias g='git'
lazy() { eval "git add -A && git commit --allow-empty-message --date='$(date)' -C HEAD && git push"; }

cht() { eval "curl cht.sh/$1"; }
mkcd() { eval "mkdir $1 && cd $1"; }
yt() { eval "mpv --ytdl-format=best[height=$1] --gapless-audio=yes $(xp)"; }

