#!/bin/sh

alias p='pacman --color=auto'
alias sp='sudo pacman -S --noconfirm'

alias cat='cat -s'
alias diff='diff --color=auto -u'
alias du='du -h'
alias df='df -h'
alias flush="sync; sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'"
alias grep='grep --color=auto -E'
alias ls='ls -v --color=auto'
alias ll='ls -lAhF'
alias o='xdg-open'
alias rd='rm -rf'
alias ssn='shutdown now'
alias xc='xsel -ib'
alias xp='xsel -ob'
alias playtime='cd ~/src/go/playground && nvim main.go'
alias testmic='arecord -vvv -f dat /dev/null'
alias testtime="gaze -c 'go test -timeout=2s' ."
alias v='nvim'
alias vimconf='nvim ~/.config/nvim/init.lua'
alias yaegi='rlwrap yaegi'

alias g='git'
lazy() { eval "git add -A && git commit --allow-empty-message --date='$(date)' -C HEAD && git push"; }

cht() { eval "curl cht.sh/$1"; }
mkcd() { eval "mkdir $1 && cd $1"; }
yt() { eval "mpv --ytdl-format=best[height=$1] --gapless-audio=yes $(xp)"; }

