#!/usr/bin/env bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export PATH="$PATH:$HOME/.local/bin:$XDG_DATA_HOME/npm/bin:$XDG_DATA_HOME/gcloud/bin:$XDG_DATA_HOME/lua/bin/"

export SUDO_ASKPASS=/usr/lib/ssh/ssh-askpass

export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

export GOPATH="$XDG_DATA_HOME/go"
export GOBIN="$HOME/.local/bin"

export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/rc"

export LC_ALL=en_US.UTF-8
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

HISTCONTROL=ignoreboth
unset HISTFILE
export LESSHISTFILE=/dev/null

export MANPAGER='nvim +Man!'
export TERMINAL=alacritty
export EDITOR=nvim
export BROWSER=firefox

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:locus=01:quote=01'
export FZF_DEFAULT_COMMAND="find . ! -path '*node_modules*' -a ! -path '*venv*' -a ! -path '*__pycache__*'"

reset='\[\e[0m\]'
b_brown='\[\e[1;33m\]'
u_purple='\[\e[4;35m\]'
PS1="${u_purple}\A${reset} ${b_brown}\w\n${reset}"

. "$XDG_CONFIG_HOME/bash/alias"
. "$XDG_CONFIG_HOME/bash/.secret"
. "$XDG_CONFIG_HOME/bash/gsdk.path"
. "$XDG_CONFIG_HOME/bash/gsdk.completion"

eval "$(direnv hook bash)"
task list
# journalctl -b -p warning
# :w !sudo tee %
